// Generates preview/src/sandbox.js from src/scene.json + src/catalog.json so the
// browser preview renders the SAME geometry, palette and catalog data as the
// shipping mod. Only the renderer differs - see the fidelity notes it prints.
//
// Regenerate: npm run gen:preview     Then: npm run preview
//
// Views: sfx | vfx | snow | gas | grouped | selected | armed | closed | empty | search | filters | pfxSfx | pfxVfx | music | radio

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SCENE = resolve(ROOT, "src", "scene.json");
const CATALOG = resolve(ROOT, "src", "catalog.json");
const SIDECAR = JSON.parse(readFileSync(CATALOG, "utf8"));
const BANLIST = resolve(ROOT, "banlist.json");
const TOOL = resolve(ROOT, "..", "main_resources", "bf6-portal-ui-preview-main");
const PREVIEW = resolve(ROOT, "preview");
const SANDBOX = resolve(PREVIEW, "src", "sandbox.js");

const VIEW_LIST = "sfx | vfx | snow | gas | grouped | selected | armed | closed | empty | search | filters | pfxSfx | pfxVfx | music | radio";

function main() {
    const scene = JSON.parse(readFileSync(SCENE, "utf8"));
    const catalog = JSON.parse(readFileSync(CATALOG, "utf8"));
    const banned = JSON.parse(readFileSync(BANLIST, "utf8")).assets.map((a) => a.name);
    // Tester descriptions and labels come from the generated files, so the
    // preview shows the same wording as the game.
    const musicDesc = JSON.parse(readFileSync(resolve(ROOT, "src", "musickeys.json"), "utf8")).desc;
    const strings = JSON.parse(readFileSync(resolve(ROOT, "src", "strings.json"), "utf8"));
    const textGen = readFileSync(resolve(ROOT, "src", "text.gen.ts"), "utf8");
    const label = (field) => {
        const m = new RegExp("\\b" + field + ': "(\\w+)"').exec(textGen);
        if (m === null || strings[m[1]] === undefined) throw new Error("gen-sandbox: no label " + field);
        return strings[m[1]];
    };
    const labels = { mtRadioHelp: label("mtRadioHelp"), mtNoteParams: label("mtNoteParams") };

    copyPreviewTool();

    const src = `// AUTO-GENERATED by tools/gen-sandbox.mjs - DO NOT EDIT BY HAND.
// Regenerate: npm run gen:preview
//
// Flip VIEW below, or pass ?view=<state> in the URL. The server hot-reloads on save.
//
//   ${VIEW_LIST}

import { initViewport, mod, UIContainer, UIText, UITextButton, UIButton } from "./renderer.js";

const VIEW = "sfx";

initViewport();

const SCENE = ${JSON.stringify(scene)};
const CATALOG = ${JSON.stringify(catalog)};
const BANNED = ${JSON.stringify(banned)};
const MUSIC_DESC = ${JSON.stringify(musicDesc)};
const LABEL = ${JSON.stringify(labels)};

// Player-wide effects registered by src/index.ts (not world objects).
const SCREEN_FX = [
  { id: "vl7gas", display: "VL7 Gas Mask", category: "Gas", effect: "ScreenEffects.VL7", soldier: "SoldierEffects.VL7Effect" },
  { id: "night", display: "Night Vision", category: "Screen", effect: "ScreenEffects.Night" },
  { id: "saturated", display: "Saturated", category: "Screen", effect: "ScreenEffects.Saturated" },
  { id: "stealth", display: "Stealth", category: "Screen", effect: "ScreenEffects.Stealth" },
];

const P = SCENE.palette;
const C = mod.CreateVector;

// ------------------------------------------------------------------ helpers

function hexToVec(hex) {
  const n = parseInt(hex.slice(1), 16);
  return C(((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255);
}

const FILL = {
  Solid: mod.UIBgFill.Solid, Blur: mod.UIBgFill.Blur,
  OutlineThin: mod.UIBgFill.OutlineThin, OutlineThick: mod.UIBgFill.OutlineThick,
  None: mod.UIBgFill.None,
};
const ANCHOR = {
  Left: mod.UIAnchor.CenterLeft, CenterLeft: mod.UIAnchor.CenterLeft,
  Right: mod.UIAnchor.CenterRight, CenterRight: mod.UIAnchor.CenterRight,
  TopLeft: mod.UIAnchor.TopLeft, TopRight: mod.UIAnchor.TopRight,
  Center: mod.UIAnchor.Center, TopCenter: mod.UIAnchor.TopCenter,
};

function fmtWindow(ms) {
  const total = Math.max(0, Math.round(ms / 1000));
  const s = total % 60, m = Math.floor(total / 60);
  const ss = s < 10 ? "0" + s : String(s);
  return m > 0 ? m + ":" + ss : "0:" + ss;
}
function trunc(s, max) { return s.length <= max ? s : s.slice(0, max - 1) + "\\u2026"; }

function resolveToken(tok, fields) {
  const body = tok.slice(2, tok.length - 2);
  const dot = body.indexOf(".");
  if (dot < 0) return body;
  const g = fields[body.slice(0, dot)];
  if (g === undefined) return body;
  const v = g[body.slice(dot + 1)];
  return v === undefined ? body : String(v);
}

function prop(n, key, fields, scope) {
  if (n.bind && n.bind[key] !== undefined) {
    const s = fields[scope];
    if (s !== undefined && s[n.bind[key]] !== undefined) return String(s[n.bind[key]]);
  }
  const raw = n[key];
  if (raw === undefined) return undefined;
  return typeof raw === "string" && raw.startsWith("{{") ? resolveToken(raw, fields) : String(raw);
}

// ------------------------------------------------------------ catalog model

// Mirrors src/ui.ts: one unified Row type across both tabs.
const ROWS = {
  sfx: CATALOG.sfx.entries.map((e) => ({ type: "sfx", entry: e })),
  vfx: [
    ...CATALOG.vfx.entries.map((e) => ({ type: "spawn", entry: e })),
    ...SCREEN_FX.map((f) => ({ type: "screen", id: f.id, display: f.display, category: f.category })),
  ],
};
// Screen-effect categories (Gas, Screen) go first, mirroring registerGroups() in src/ui.ts.
const VFX_GROUPS = [...SCREEN_FX.map((f) => f.category).filter((c2, i, a) => a.indexOf(c2) === i), ...CATALOG.vfx.categories];
const GROUPS = { sfx: CATALOG.sfx.categories, vfx: VFX_GROUPS.filter((c2, i, a) => a.indexOf(c2) === i) };

const rowKey = (r) => (r.type === "screen" ? "screen:" + r.id : r.entry.name);
const rowDisplay = (r) => (r.type === "screen" ? r.display : r.entry.display);
const rowCategory = (r) => (r.type === "screen" ? r.category : r.entry.category);

function listFor(tab, group, f) {
  const q = (f.query || "").trim().toLowerCase();
  const name = q === "" ? (group === 0 ? "*" : (GROUPS[tab][group - 1] ?? "")) : "*";
  return ROWS[tab].filter((r) => {
    if (name !== "*" && rowCategory(r) !== name) return false;
    if (tab === "sfx") {
      if (f.dim && r.entry.dim !== f.dim) return false;
      if (f.kind && r.entry.kind !== f.kind) return false;
    } else {
      if (f.vfx === "world" && r.type !== "spawn") return false;
      if (f.vfx === "screen" && r.type !== "screen") return false;
    }
    if (q === "") return true;
    return rowDisplay(r).toLowerCase().includes(q) || rowKey(r).toLowerCase().includes(q);
  });
}
function groupIndex(tab, name) {
  const i = GROUPS[tab].indexOf(name);
  return i < 0 ? 0 : i + 1;
}
const perPage = SCENE.grid.rows;
const pageCount = (n) => Math.max(1, Math.ceil(n / perPage));

// ------------------------------------------------------------- tester sample
// A representative MUSIC / RADIO state, mirroring src/tester.ts testerFields().
// Layout-only, like the rest of the preview: the values are the owner's reference
// screenshot (Core_PhaseEnded, IsWinning 1, volume 1.3), not live music data.
function testerSample(tab) {
  const radio = tab === "radio";
  const rows = radio
    ? [["Radio_Biome", "0"], ["Radio_Channel", "3"], ["Radio_ContinueQueueOnTrackEnd", "1"], ["Radio_LoopQueuedTracks", "0"], ["Radio_QueueTrackNumber", "2"]]
    : [["Core_IsWinning", "1"], ["Core_PhaseUrgency", "0"], ["Core_Sector", "0"], ["Core_Urgency", "0"]];
  const f = {
    mtTitle: radio ? "RADIO" : "TRACK",
    mtPkgArrows: radio ? "0" : "1",
    mtPkg: "PACKAGE: " + (radio ? "RADIO" : "CORE"),
    mtEvent: radio ? "RADIO STATION" : "Core_PhaseEnded",
    mtEventIdx: radio ? "QUEUE: 3 track(s). Last added: Reggaeton #1" : "TRACK 7 / 10",
    mtPrevLabel: radio ? "CLEAR QUEUE" : "|<",
    mtPlayLabel: "PLAY",
    mtStopLabel: "STOP",
    mtNextLabel: radio ? "NEXT TRACK" : ">|",
    mtEventDesc: radio ? LABEL.mtRadioHelp : MUSIC_DESC["Core_PhaseEnded"],
    mtParamNote: LABEL.mtNoteParams,
    mtVol: radio ? "1" : "1.3",
    mtLast: radio ? "SetMusicParam(Radio_QueueTrackNumber, 2)" : "PlayMusic(Core_PhaseEnded)",
    mtLoadLabel: radio ? "LOAD RADIO" : "CORE LOADED",
    mtLoadBg: radio ? P.amber : P.green,
    mtTargetLabel: "FOR: ME",
    mtTargetBg: P.row,
    mtQueueOn: radio ? "1" : "0",
    mtQueueLabel: "QUEUE TRACK 2",
  };
  if (radio) f.mtParamNote = "CHANNEL 3 = Reggaeton    BIOME = Gibraltar (channel 4 only)";
  for (let i = 0; i < 5; i++) {
    const r = rows[i];
    f["mtP" + i + "On"] = r === undefined ? "0" : "1";
    f["mtP" + i + "Label"] = r === undefined ? "" : r[0] + " :";
    f["mtP" + i + "Val"] = r === undefined ? "" : r[1];
    f["mtP" + i + "Desc"] = r === undefined ? "" : MUSIC_DESC[r[0]];
  }
  return f;
}

// ------------------------------------------------------------- view selection

const view = new URLSearchParams(location.search).get("view") || VIEW;

function pick() {
  const base = { tab: "sfx", group: 0, page: 0, selected: "", armed: "", scale: 1.0, amp: "0.80", rng: "40", open: true, spawned: 0, searchOpen: false, kbPage: 0, query: "", dim: "", kind: "", vfx: "", sel: 0 };
  switch (view) {
    case "vfx": return { ...base, tab: "vfx" };
    case "snow": return { ...base, tab: "vfx", group: groupIndex("vfx", "Snow") };
    case "gas": return { ...base, tab: "vfx", group: groupIndex("vfx", "Gas") };
    case "grouped": return { ...base, tab: "sfx", group: groupIndex("sfx", "Soldier_Melee") };
    case "selected": return { ...base, tab: "vfx", scale: 1.8, selected: rowKey(listFor("vfx", 0, { query: "", dim: "", kind: "", vfx: "" })[3]) };
    case "armed": return { ...base, tab: "vfx", open: false, scale: 2.4, spawned: 7, armed: rowKey(listFor("vfx", 0, { query: "", dim: "", kind: "", vfx: "" })[3]), selected: rowKey(listFor("vfx", 0, { query: "", dim: "", kind: "", vfx: "" })[3]) };
    case "closed": return { ...base, open: false, armed: rowKey(ROWS.sfx[0]), spawned: 0 };
    case "empty": return { ...base, tab: "vfx", group: GROUPS.vfx.length - 1 };
    case "search": return { ...base, tab: "sfx", searchOpen: true, query: "explos" };
      case "pfxSfx": return { ...base, tab: "sfx", searchOpen: true, kbPage: 1 };
      case "pfxVfx": return { ...base, tab: "vfx", searchOpen: true, kbPage: 1 };
    case "filters": return { ...base, tab: "sfx", dim: "3d", kind: "loop" };
    case "music": return { ...base, tab: "music" };
    case "radio": return { ...base, tab: "radio" };
    default: return base;
  }
}

const V = pick();
const TESTER = V.tab === "music" || V.tab === "radio";
// The tester tabs have no catalog list; listFor() only knows sfx / vfx.
const list = TESTER ? [] : listFor(V.tab, V.group, V);
const page = list.slice(V.page * perPage, V.page * perPage + perPage);
const total = TESTER ? 0 : ROWS[V.tab].length;
const shown = list.length;
const armedLabel = V.armed === "" ? "" : (rowDisplay(list.find((r) => rowKey(r) === V.armed) ?? { type: "screen", display: V.armed, category: "" }));
const selLabel = V.selected === "" ? "no selection" : (rowDisplay(list.find((r) => rowKey(r) === V.selected) ?? { type: "screen", display: V.selected, category: "" }));

const chromeFields = {
  menuOpen: V.open ? "1" : "0",
  searchOpen: V.searchOpen ? "1" : "0",
  queryText: V.query === "" ? "type to search" : V.query,
  queryEmpty: V.query === "" ? "1" : "0",
  queryCount: shown + " of " + total,
  filterSummary: "FILTERS: " + ((V.dim || V.kind || V.vfx) ? [V.dim.toUpperCase(), V.kind === "loop" ? "LOOP" : V.kind === "oneshot" ? "ONE-SHOT" : "", V.vfx === "world" ? "WORLD" : V.vfx === "screen" ? "PLAYER" : ""].filter(Boolean).join(" + ") : "no filter"),
  sfxParams: V.tab === "sfx" ? "1" : "0",
  vfxParams: V.tab === "sfx" ? "0" : "1",
  tabSfxColor: V.tab === "sfx" ? "#FFFFFF" : P.inkDim,
  tabSfxBg: V.tab === "sfx" ? P.hot : P.line,
  tabVfxColor: V.tab === "vfx" ? "#FFFFFF" : P.inkDim,
  tabVfxBg: V.tab === "vfx" ? P.hot : P.line,
  tabFavColor: V.tab === "fav" ? "#FFFFFF" : P.inkDim,
  tabFavBg: V.tab === "fav" ? P.hot : P.line,
  tabMusicColor: V.tab === "music" ? "#FFFFFF" : P.inkDim,
  tabMusicBg: V.tab === "music" ? P.hot : P.line,
  tabRadioColor: V.tab === "radio" ? "#FFFFFF" : P.inkDim,
  tabRadioBg: V.tab === "radio" ? P.hot : P.line,
  // The mod starts with debug logging on (src/diag.ts).
  debugLabel: "DEBUG ON",
  debugColor: P.green,
  debugBg: P.panel,
  browserOn: TESTER ? "0" : "1",
  testerOn: TESTER ? "1" : "0",
  ...testerSample(V.tab),
  headBadge: V.tab === "sfx" ? "SPATIALITY" : "SCALE",
  armed: V.armed === "" ? "NOTHING ARMED" : "ARMED: " + trunc(armedLabel, 40),
  armedColor: V.armed === "" ? P.faint : P.green,
  railSummary: shown === total ? total + " ITEMS" : shown + " / " + total + " MATCH",
  page: "PAGE " + (V.page + 1) + " / " + pageCount(list.length),
  amp: V.amp,
  rng: V.rng,
  scale: V.scale.toFixed(2) + "x",
  spawned: "SPAWNED IN WORLD: " + V.spawned,
  selInfo: trunc(selLabel, 34),
  selectLabel: V.selected === "" ? "SELECT AN ITEM" : V.armed === V.selected ? "SELECTED \\u2713" : "SELECT",
  selectBg: V.selected === "" ? P.row : V.armed === V.selected ? P.green : P.blue,
  hint: V.tab === "music"
    ? "LOAD the package first, then pick a track and PLAY. Params and VOLUME apply live; PLAY re-sends them first."
    : V.tab === "radio"
    ? "LOAD RADIO, pick a channel, pick a track number and QUEUE TRACK it, then PLAY. The queue starts empty."
    : !V.open
    ? "MENU CLOSED \u2014 aim (right mouse) to reopen \u00b7 fire (left mouse) to spawn what is armed"
    : V.tab === "vfx"
      ? (V.selected === ""
        ? "Pick an effect, set SCALE, then SELECT. The menu closes and the gadget arms it."
        : "Fire to place it at your aim point. SELECT closes the menu, aim reopens it to undo or delete all.")
      : (V.selected === ""
        ? "\u25b6 auditions the sound straight away. SELECT arms it and closes the menu."
        : "Fire to place the sound at your aim point. Aim reopens the menu to pick another."),};

function rowFields(r) {
  const key = rowKey(r);
  const selected = key === V.selected;
  const armed = key === V.armed;
  const selLabel = armed ? "ARMED" : "SELECT";
  const selColor = armed ? "#FFFFFF" : P.ink;
  const selBg = armed ? P.green : selected ? P.rowSel : P.row;
  const head = {
    bg: selected ? P.rowSel : P.row,
    name: rowDisplay(r),
    nameColor: selected ? P.ink : P.inkDim,
    category: rowCategory(r),
    selLabel, selColor, selBg,
  };

  if (r.type === "sfx") {
    const e = r.entry;
    const is3d = e.dim === "3d";
    const isLoop = e.kind === "loop";
    const b1c = is3d ? P.blue : P.amber;
    const b2c = isLoop ? P.green : P.grey;
    return { ...head, actGlyph: "P", actColor: "#FFFFFF", actBg: b1c, b1: is3d ? "3D" : "2D", b1Color: b1c, b1Bg: b1c, b2: isLoop ? "LOOP" : "ONE", b2Color: b2c, b2Bg: b2c };
  }
  const world = r.type === "spawn";
  const b1c = world ? P.violet : P.green;
  const b2c = world ? P.blue : P.amber;
  return { ...head, actGlyph: world ? "S" : "T", actColor: "#FFFFFF", actBg: b1c, b1: world ? V.scale.toFixed(2) + "x" : "PLAYER", b1Color: b1c, b1Bg: b1c, b2: world ? "WORLD" : "EFFECT", b2Color: b2c, b2Bg: b2c };
}

// ------------------------------------------------------------------- render

const BASE = { anchor: mod.UIAnchor.TopLeft, visible: true, parent: null, depth: mod.UIDepth.AboveGameUI, receiver: {} };

function add(n, ox, oy, fields, scope) {
  let w = n.w ?? 0;
  if (n.wScale !== undefined) w = w * Number(prop(n, n.wScale, fields, scope) ?? 0);

  const common = {
    ...BASE,
    position: { x: ox + n.x, y: oy + n.y },
    size: { width: Math.max(0, w), height: n.h ?? 0 },
    bgColor: hexToVec(prop(n, "bg", fields, scope) ?? "#000000"),
    bgAlpha: Number(prop(n, "bgAlpha", fields, scope) ?? 1),
    bgFill: FILL[prop(n, "fill", fields, scope)] ?? mod.UIBgFill.None,
  };

  if (n.k === "container") return new UIContainer(common);

  const tSize = Number(prop(n, "textSize", fields, scope) ?? 7);
  const tColor = hexToVec(prop(n, n.k === "text" ? "color" : "textColor", fields, scope) ?? "#FFFFFF");
  const tAnchor = ANCHOR[prop(n, "align", fields, scope)] ?? mod.UIAnchor.Center;

  if (n.k === "text") {
    return new UIText({ ...common, message: prop(n, "text", fields, scope) ?? "", textSize: tSize, textColor: tColor, textAlpha: Number(prop(n, "textAlpha", fields, scope) ?? 1), textAnchor: tAnchor, wrap: n.wrap === true });
  }
  const isText = n.k === "textbutton";
  return new (isText ? UITextButton : UIButton)({
    ...common,
    message: isText ? prop(n, "text", fields, scope) ?? "" : "",
    textSize: tSize, textColor: tColor, textAnchor: tAnchor,
    baseColor: hexToVec(prop(n, "bg", fields, scope) ?? "#000000"),
    baseAlpha: Number(prop(n, "bgAlpha", fields, scope) ?? 1),
    enabled: n.enabled !== false,
  });
}

function walk(nodes, ox, oy, fields, scope) {
  const groupVisible = {};
  // A group may carry its own origin; children are relative to it.
  const groupOrigin = {};
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i];
    if (n.k === "group") {
      // A group nested inside a hidden group is itself hidden. buildNodes() in
      // ui.ts gets this from recursion; walk() is flat, so it has to check.
      const id = n.id ?? "g" + i;
      if (n.parent !== undefined && groupVisible[n.parent] === false) {
        groupVisible[id] = false;
        groupOrigin[id] = { x: 0, y: 0 };
        continue;
      }
      const bound = prop(n, "visible", fields, scope);
      groupVisible[id] = bound !== undefined ? bound !== "0" : n.visible !== false;
      groupOrigin[id] = { x: n.x, y: n.y };
      continue;
    }
    let gx = 0, gy = 0;
    if (n.parent !== undefined) {
      if (groupVisible[n.parent] === false) continue;
      const o = groupOrigin[n.parent];
      if (o) { gx = o.x; gy = o.y; }
    }

    if (n.k === "repeat") {
      const tpl = n.template;
      if (!tpl) continue;
      const count = n.count ?? 0, cols = n.cols ?? 0, gap = n.gap ?? 0;
      const gapX = n.gapX ?? gap, gapY = n.gapY ?? gap;
      const tw = tpl.w ?? 0, th = tpl.h ?? 0;
      for (let j = 0; j < count; j++) {
        const cx = cols > 0 ? (j % cols) * (tw + gapX) : j * (tw + gap);
        const cy = cols > 0 ? Math.floor(j / cols) * (th + gapY) : 0;
        add({ ...tpl, x: tpl.x + cx, y: tpl.y + cy }, ox + gx + n.x, oy + gy + n.y, fields, scope);
      }
      continue;
    }
    add(n, ox + gx, oy + gy, fields, scope);
  }
}

const GF = { sh: P, f: chromeFields };
walk(SCENE.screen, 0, 0, GF, "f");
if (V.open && !TESTER) {
// rail: ALL is a static text row, the groups are buttons below it
const NOF = { query: "", dim: "", kind: "", vfx: "" };
const counts = [listFor(V.tab, 0, NOF).length];
for (let i = 0; i < GROUPS[V.tab].length; i++) counts.push(listFor(V.tab, i + 1, NOF).length);
const groupTotal = counts.length - 1;
const groupRows = SCENE.rail.visibleRows - 1;
const railX = SCENE.rail.x + SCENE.rail.rowPadX;
const railOf = (label, count, active) => ({
  sh: P,
  rail: { label: label + "   " + count, color: active ? "#FFFFFF" : P.inkDim, bg: active ? P.hot : P.line },
});
walk([{ ...SCENE.railRow, k: "text" }], railX, SCENE.rail.rowsY, railOf("ALL", counts[0], false), "rail");
for (let slot = 0; slot < groupRows; slot++) {
  const gi = slot;
  if (gi >= groupTotal) continue;
  walk([{ ...SCENE.railRow }], railX, SCENE.rail.rowsY + (slot + 1) * SCENE.rail.rowH, railOf(GROUPS[V.tab][gi], counts[gi + 1], V.group === gi), "rail");
}



// filter chips + search button (only when open)
const chips = V.tab === "sfx" ? SCENE.filterBarSpec.sfx : SCENE.filterBarSpec.vfx;
const chipAct = (key, val) => (val === "" ? "fa" : key === "dim" ? (val === "3d" ? "fd3" : "fd2") : key === "kind" ? (val === "loop" ? "fl" : "fo") : val === "world" ? "fw" : "fp");
for (let i = 0; i < chips.length; i++) {
  const c = chips[i];
  const a = chipAct(c.key, c.val);
  const on = a === "fa" ? (V.dim === "" && V.kind === "" && V.vfx === "") : a === "fd3" ? V.dim === "3d" : a === "fd2" ? V.dim === "2d" : a === "fl" ? V.kind === "loop" : a === "fo" ? V.kind === "oneshot" : a === "fw" ? V.vfx === "world" : V.vfx === "screen";
  add({ k: "textbutton", x: SCENE.filterBarSpec.chipX + i * (SCENE.filterBarSpec.chipW + SCENE.filterBarSpec.gap), y: SCENE.filterBarSpec.chipY, w: SCENE.filterBarSpec.chipW, h: SCENE.filterBarSpec.chipH, fill: "Solid", bg: on ? P.blue : P.row, bgAlpha: 1, text: c.label, textSize: 13, textColor: on ? "#FFFFFF" : P.inkDim, align: "Center" }, 0, 0, { sh: P, f: { text: c.label, textColor: on ? "#FFFFFF" : P.inkDim, bg: on ? P.blue : P.row } }, "f");
}
add({ k: "textbutton", x: SCENE.filterBarSpec.searchX, y: SCENE.filterBarSpec.searchY, w: SCENE.filterBarSpec.searchW, h: SCENE.filterBarSpec.searchH, fill: "Solid", bg: V.searchOpen ? P.green : P.panel, bgAlpha: 1, text: V.searchOpen ? "KEYBOARD OPEN" : "SEARCH", textSize: 14, textColor: V.searchOpen ? "#FFFFFF" : P.ink, align: "Center" }, 0, 0, { sh: P, f: { text: V.searchOpen ? "KEYBOARD OPEN" : "SEARCH", textColor: V.searchOpen ? "#FFFFFF" : P.ink, bg: V.searchOpen ? P.green : P.panel } }, "f");

// rows (hidden while the keyboard overlay is up)
if (!V.searchOpen) {
  for (let i = 0; i < page.length; i++) {
    walk(SCENE.row, SCENE.grid.originX, SCENE.grid.originY + i * SCENE.grid.rowH, { sh: P, r: rowFields(page[i]) }, "r");
  }
}

// simulated keyboard
if (V.searchOpen) {
  const kb = SCENE.keyboard;
  add({ k: "container", x: kb.x, y: kb.y, w: kb.w, h: kb.h, fill: "Solid", bg: P.shell, bgAlpha: 1 }, 0, 0, { sh: P }, "f");
  add({ k: "text", x: kb.x + 16, y: kb.queryY, w: kb.w - 420, h: kb.queryH, text: V.query === "" ? (V.kbPage === 1 ? "tap a prefix, then refine on ABC" : "type to search") : V.query, textSize: 20, textColor: V.query === "" ? P.faint : P.ink, textAnchor: mod.UIAnchor.CenterLeft, align: "Left" }, 0, 0, { sh: P, f: { text: "", textColor: P.ink, bg: "#000000" } }, "f");
  add({ k: "text", x: kb.x + kb.w - 396, y: kb.queryY, w: 380, h: kb.queryH, text: shown + " of " + total + " MATCH", textSize: 14, textColor: P.muted, textAnchor: mod.UIAnchor.CenterRight, align: "Right" }, 0, 0, { sh: P, f: { text: "", textColor: P.muted, bg: "#000000" } }, "f");
  if (V.kbPage === 1) {
    const pg = kb.prefixGrid;
    const all = V.tab === "sfx" ? CATALOG.sfxPrefixes : CATALOG.vfxPrefixes;
    const n = Math.min(all.length, pg.max);
    for (let i = 0; i < n; i++) {
      const e = all[i];
      const col = i % pg.cols, row = Math.floor(i / pg.cols);
      if (row >= pg.rows) break;
      add({ k: "textbutton", x: pg.x0 + col * (pg.w + pg.gap), y: pg.rowY[row], w: pg.w, h: pg.h, fill: "Solid", bg: P.row, bgAlpha: 1, text: e.token, textSize: 12, textColor: P.ink, align: "Center" }, 0, 0, { sh: P, f: { text: e.token, textColor: P.ink, bg: P.row } }, "f");
    }
  } else {
    for (let r = 0; r < kb.rows.length; r++) {
      const chars = kb.rows[r];
      for (let i = 0; i < chars.length; i++) {
        add({ k: "textbutton", x: kb.x0 + i * (kb.keyW + kb.gap), y: kb.rowY[r], w: kb.keyW, h: kb.keyH, fill: "Solid", bg: P.row, bgAlpha: 1, text: chars[i], textSize: 20, textColor: P.ink, align: "Center" }, 0, 0, { sh: P, f: { text: chars[i], textColor: P.ink, bg: P.row } }, "f");
      }
    }
  }
  let bx = kb.x0;
  for (const b of kb.bottom) {
    const isDone = b.action === "done";
    const isPage = b.action === "page";
    const label = isPage ? (V.kbPage === 1 ? "ABC KEYS" : "PREFIXES") : b.label;
    const bg = isDone ? P.green : b.action === "clr" ? P.redDim : isPage ? P.violet : P.row;
    add({ k: "textbutton", x: bx, y: kb.bottomY, w: b.w, h: kb.bottomH, fill: "Solid", bg: bg, bgAlpha: 1, text: label, textSize: 17, textColor: isDone ? "#FFFFFF" : P.ink, align: "Center" }, 0, 0, { sh: P, f: { text: label, textColor: isDone ? "#FFFFFF" : P.ink, bg: bg } }, "f");
    bx += b.w + kb.gap;
  }
}
} // end if (V.open)

// Opt-in with ?notes=1. Off by default: this is dev scaffolding, not part of the HUD, and it sits directly under the panel where it reads as if it were.
if (new URLSearchParams(location.search).get("notes") === "1") {
  const notes = [
    "VIEW=" + view + "   (" + ${JSON.stringify(VIEW_LIST)} + ")",
    "SFX " + CATALOG.sfx.total + " across " + CATALOG.sfx.categories.length + " groups   |   VFX " + CATALOG.vfx.total + " across " + CATALOG.vfx.categories.length + " groups + " + SCREEN_FX.length + " player-wide",
    "banned and filtered out of the catalog: " + BANNED.length + "   |   snow FX: " + CATALOG.vfx.entries.filter((e) => e.name.includes("Snow")).length,
    "",
    "FIDELITY GAPS (Portal cannot do these; nothing below is faked):",
    "  rounded corners   -> square (UIBgFill has no border-radius)",
    "  diagonal stripes  -> alternating vertical slivers (containers cannot rotate)",
    "  any texture/image -> duration bar + meter slivers; UIImageType is a fixed 8-icon enum, no upload",
    "  outer drop shadow -> OutlineThin inset border",
    "  clipboard         -> no API, so the enum name is a static reference",
    "  circular buttons  -> square, with base/hover/pressed/focused colour states",
    "  U+25B6 / U+25C6 / U+2630 may be missing from the BF Text font -> falls back to plain letters",
  ];
  const box = new UIContainer({ ...BASE, position: { x: 20, y: 740 }, size: { width: 1120, height: 40 }, bgColor: hexToVec(P.panel), bgAlpha: 0.92, bgFill: mod.UIBgFill.Solid });
  for (let i = 0; i < notes.length; i++) {
    new UIText({ ...BASE, parent: box, position: { x: 6, y: i * 3.6 }, size: { width: 1108, height: 4 }, message: notes[i], textSize: 2.6, textColor: hexToVec(i === 0 ? P.amber : P.faint), textAlpha: 1, textAnchor: mod.UIAnchor.CenterLeft, bgColor: hexToVec("#000000"), bgAlpha: 0, bgFill: mod.UIBgFill.None });
  }
}
`;

    mkdirSync(dirname(SANDBOX), { recursive: true });
    writeFileSync(SANDBOX, src, "utf8");
    console.log(`  wrote ${SANDBOX}`);
    console.log(`  views: ${VIEW_LIST}`);
    console.log(`  sfx ${catalog.sfx.total}/${catalog.sfx.categories.length} groups | vfx ${catalog.vfx.total}/${catalog.vfx.categories.length} groups + ${4} player-wide`);
    console.log(`  run: npm run preview  ->  http://localhost:8081/`);
}

function copyPreviewTool() {
    if (!existsSync(TOOL)) {
        console.warn(`  WARNING: preview tool not found at ${TOOL}; skipped copy.`);
        return;
    }
    for (const f of ["index.html", "server.mjs"]) copyFileSync(resolve(TOOL, f), resolve(PREVIEW, f));

    // The upstream index.html opens a long-lived SSE connection for hot reload,
    // which stops headless Chrome/Edge from ever reaching network idle, so
    // --screenshot hangs forever. Re-apply the ?nohot=1 gate after every copy.
    const idx = resolve(PREVIEW, "index.html");
    let html = readFileSync(idx, "utf8");
    const anchor = '        const sse = new EventSource("/__reload");';
    if (html.includes(anchor) && !html.includes("nohot")) {
        html = html.replace(
            anchor,
            '        if (new URLSearchParams(location.search).get("nohot") === "1") return;\n' + anchor
        );
        writeFileSync(idx, html, "utf8");
        console.log("  index.html: re-applied ?nohot=1 gate (needed for headless screenshots)");
    }
    mkdirSync(resolve(PREVIEW, "src"), { recursive: true });
    if (!existsSync(resolve(PREVIEW, "src", "renderer.js"))) copyFileSync(resolve(TOOL, "src", "renderer.js"), resolve(PREVIEW, "src", "renderer.js"));
    const assets = resolve(TOOL, "assets");
    if (existsSync(assets)) {
        mkdirSync(resolve(PREVIEW, "assets"), { recursive: true });
        for (const f of readdirSync(assets)) copyFileSync(resolve(assets, f), resolve(PREVIEW, "assets", f));
    }
    patchRenderer();
    console.log("  preview tool synced");
}

// The upstream renderer's UIText never applies params.textSize, while
// UITextButton does. That makes every plain-text element render at browser
// default size regardless of the layout, which silently invalidates any type
// tuning done against the preview. Re-apply the fix after every copy.
function patchRenderer() {
    const rp = resolve(PREVIEW, "src", "renderer.js");
    if (!existsSync(rp)) return;
    let src = readFileSync(rp, "utf8");
    if (src.includes("TEXT_SIZE_PATCH")) return;
    const target = `    s.fontFamily = "'BF Text', 'Segoe UI', 'Arial Narrow', sans-serif";\n    s.letterSpacing = "0.5px";`;
    const patched = `    s.fontFamily = "'BF Text', 'Segoe UI', 'Arial Narrow', sans-serif";\n    // TEXT_SIZE_PATCH: UIText honoured textSize like UITextButton already did.\n    if (params.textSize) s.fontSize = params.textSize + "px";\n    s.letterSpacing = "0.5px";`;
    if (!src.includes(target)) {
        console.warn("  WARNING: renderer.js patch anchor not found; UIText will ignore textSize.");
        return;
    }
    src = src.replace(target, patched);

    // Also: UITextButton hardcodes justifyContent/alignItems to centre, so
    // textAnchor is ignored and every button label centres regardless. Make it
    // honour the anchor the same way UIText does.
    const btnAnchorTarget = `    s.justifyContent = "center";\n    s.textAlign = "center";\n    s.fontFamily = "'BF Text', 'Segoe UI', 'Arial Narrow', sans-serif";\n    s.fontWeight = "700";`;
    const btnAnchorPatched = `    s.justifyContent = "center";\n    s.textAlign = "center";\n    s.fontFamily = "'BF Text', 'Segoe UI', 'Arial Narrow', sans-serif";\n    s.fontWeight = "700";\n    // TEXT_ANCHOR_PATCH\n    if (params.textAnchor) {\n      const ta = params.textAnchor;\n      if (ta.includes("Left")) s.justifyContent = "flex-start";\n      else if (ta.includes("Right")) s.justifyContent = "flex-end";\n      if (ta.includes("Top")) s.alignItems = "flex-start";\n      else if (ta.includes("Bottom")) s.alignItems = "flex-end";\n    }`;
    if (src.includes(btnAnchorTarget)) src = src.replace(btnAnchorTarget, btnAnchorPatched);
    writeFileSync(rp, src, "utf8");
    console.log("  renderer.js: UIText honours textSize; UITextButton honours textAnchor");
}
main();
