// GENERATED by tools/gen-music.mjs from types_original/mod/index.d.ts -- do not edit.
//
// Every music package, its events, its parameters and their (guessed) ranges.
// `key` fields are strings.json keys for the on-screen names.

export interface MusicParamSpec {
    readonly name: string;
    readonly param: mod.MusicParams;
    readonly key: string;
    readonly min: number;
    readonly max: number;
    readonly step: number;
    readonly def: number;
}

export interface MusicEventSpec {
    readonly name: string;
    readonly event: mod.MusicEvents;
    readonly key: string;
}

export interface MusicPackageSpec {
    readonly name: string;
    readonly pkg: mod.MusicPackages;
    readonly key: string;
    /** The package's own *_Stop event, sent by STOP. Not in `events`. */
    readonly stop: mod.MusicEvents;
    readonly stopKey: string;
    readonly events: readonly MusicEventSpec[];
    /** The package's *_Amplitude param: the VOLUME control. Not in `params`. */
    readonly amp: MusicParamSpec;
    readonly params: readonly MusicParamSpec[];
}

export const PARAM_SLOTS = 5;

export const MUSIC_PACKAGES: readonly MusicPackageSpec[] = [
    {
        name: "BR",
        pkg: mod.MusicPackages.BR,
        key: "sxM00",
        stop: mod.MusicEvents.BR_Stop,
        stopKey: "sxM01",
        events: [
            { name: "BR_InsertionCinematic_Dropzone_Loop", event: mod.MusicEvents.BR_InsertionCinematic_Dropzone_Loop, key: "sxM02" },
            { name: "BR_InsertionCinematic_Loop", event: mod.MusicEvents.BR_InsertionCinematic_Loop, key: "sxM03" },
            { name: "BR_InsertionJump", event: mod.MusicEvents.BR_InsertionJump, key: "sxM04" },
            { name: "BR_InsertionLanding", event: mod.MusicEvents.BR_InsertionLanding, key: "sxM05" },
            { name: "BR_LastTwoSquads", event: mod.MusicEvents.BR_LastTwoSquads, key: "sxM06" },
            { name: "BR_Loss_Early_Loop", event: mod.MusicEvents.BR_Loss_Early_Loop, key: "sxM07" },
            { name: "BR_Loss_EndOfRound_Loop", event: mod.MusicEvents.BR_Loss_EndOfRound_Loop, key: "sxM08" },
            { name: "BR_Loss_SecondPlace_Loop", event: mod.MusicEvents.BR_Loss_SecondPlace_Loop, key: "sxM09" },
            { name: "BR_Pause", event: mod.MusicEvents.BR_Pause, key: "sxM10" },
            { name: "BR_RespawnSecondChance", event: mod.MusicEvents.BR_RespawnSecondChance, key: "sxM11" },
            { name: "BR_RespawnTower", event: mod.MusicEvents.BR_RespawnTower, key: "sxM12" },
            { name: "BR_Unpause", event: mod.MusicEvents.BR_Unpause, key: "sxM13" },
            { name: "BR_WonRound_Loop", event: mod.MusicEvents.BR_WonRound_Loop, key: "sxM14" },
            { name: "BRGauntlet_LobbyFilled", event: mod.MusicEvents.BRGauntlet_LobbyFilled, key: "sxM15" },
            { name: "BRGauntlet_WaitingForPlayers_Loop", event: mod.MusicEvents.BRGauntlet_WaitingForPlayers_Loop, key: "sxM16" },
        ],
        amp: { name: "BR_Amplitude", param: mod.MusicParams.BR_Amplitude, key: "sxM17", min: 0, max: 2, step: 0.1, def: 1 },
        params: [
            { name: "BRGauntlet_LobbyTimerRemaining", param: mod.MusicParams.BRGauntlet_LobbyTimerRemaining, key: "sxM18", min: 0, max: 300, step: 10, def: 60 },
        ],
    },
    {
        name: "Core",
        pkg: mod.MusicPackages.Core,
        key: "sxM19",
        stop: mod.MusicEvents.Core_Stop,
        stopKey: "sxM20",
        events: [
            { name: "Core_Deploy_Loop", event: mod.MusicEvents.Core_Deploy_Loop, key: "sxM21" },
            { name: "Core_EndOfRound_Loop", event: mod.MusicEvents.Core_EndOfRound_Loop, key: "sxM22" },
            { name: "Core_LastPhaseBegin", event: mod.MusicEvents.Core_LastPhaseBegin, key: "sxM23" },
            { name: "Core_Overtime_Loop", event: mod.MusicEvents.Core_Overtime_Loop, key: "sxM24" },
            { name: "Core_PauseMenu_Loop", event: mod.MusicEvents.Core_PauseMenu_Loop, key: "sxM25" },
            { name: "Core_PhaseBegin", event: mod.MusicEvents.Core_PhaseBegin, key: "sxM26" },
            { name: "Core_PhaseEnded", event: mod.MusicEvents.Core_PhaseEnded, key: "sxM27" },
            { name: "Core_Stinger_Negative", event: mod.MusicEvents.Core_Stinger_Negative, key: "sxM28" },
            { name: "Core_Stinger_Positive", event: mod.MusicEvents.Core_Stinger_Positive, key: "sxM29" },
            { name: "Core_Stinger_RankUp", event: mod.MusicEvents.Core_Stinger_RankUp, key: "sxM30" },
        ],
        amp: { name: "Core_Amplitude", param: mod.MusicParams.Core_Amplitude, key: "sxM31", min: 0, max: 2, step: 0.1, def: 1 },
        params: [
            { name: "Core_IsWinning", param: mod.MusicParams.Core_IsWinning, key: "sxM32", min: 0, max: 1, step: 1, def: 0 },
            { name: "Core_PhaseUrgency", param: mod.MusicParams.Core_PhaseUrgency, key: "sxM33", min: 0, max: 1, step: 0.1, def: 0 },
            { name: "Core_Sector", param: mod.MusicParams.Core_Sector, key: "sxM34", min: 0, max: 10, step: 1, def: 0 },
            { name: "Core_Urgency", param: mod.MusicParams.Core_Urgency, key: "sxM35", min: 0, max: 1, step: 0.1, def: 0 },
        ],
    },
    {
        name: "Gauntlet",
        pkg: mod.MusicPackages.Gauntlet,
        key: "sxM36",
        stop: mod.MusicEvents.Gauntlet_Stop,
        stopKey: "sxM37",
        events: [
            { name: "Gauntlet_Deploy", event: mod.MusicEvents.Gauntlet_Deploy, key: "sxM38" },
            { name: "Gauntlet_Loss_FinalMission_Loop", event: mod.MusicEvents.Gauntlet_Loss_FinalMission_Loop, key: "sxM39" },
            { name: "Gauntlet_Loss_Loop", event: mod.MusicEvents.Gauntlet_Loss_Loop, key: "sxM40" },
            { name: "Gauntlet_MissionBriefing_Final", event: mod.MusicEvents.Gauntlet_MissionBriefing_Final, key: "sxM41" },
            { name: "Gauntlet_MissionBriefing_One", event: mod.MusicEvents.Gauntlet_MissionBriefing_One, key: "sxM42" },
            { name: "Gauntlet_MissionBriefing_Three", event: mod.MusicEvents.Gauntlet_MissionBriefing_Three, key: "sxM43" },
            { name: "Gauntlet_MissionBriefing_Two", event: mod.MusicEvents.Gauntlet_MissionBriefing_Two, key: "sxM44" },
            { name: "Gauntlet_Pause", event: mod.MusicEvents.Gauntlet_Pause, key: "sxM45" },
            { name: "Gauntlet_Qualified_Loop", event: mod.MusicEvents.Gauntlet_Qualified_Loop, key: "sxM46" },
            { name: "Gauntlet_Qualified_Outro", event: mod.MusicEvents.Gauntlet_Qualified_Outro, key: "sxM47" },
            { name: "Gauntlet_Unpause", event: mod.MusicEvents.Gauntlet_Unpause, key: "sxM48" },
            { name: "Gauntlet_Urgency", event: mod.MusicEvents.Gauntlet_Urgency, key: "sxM49" },
            { name: "Gauntlet_Urgency_FinalMission", event: mod.MusicEvents.Gauntlet_Urgency_FinalMission, key: "sxM50" },
            { name: "Gauntlet_WonOperation_Loop", event: mod.MusicEvents.Gauntlet_WonOperation_Loop, key: "sxM51" },
        ],
        amp: { name: "Gauntlet_Amplitude", param: mod.MusicParams.Gauntlet_Amplitude, key: "sxM52", min: 0, max: 2, step: 0.1, def: 1 },
        params: [
        ],
    },
    {
        name: "Radio",
        pkg: mod.MusicPackages.Radio,
        key: "sxM53",
        stop: mod.MusicEvents.Radio_Stop,
        stopKey: "sxM54",
        events: [
            { name: "Radio_ClearQueue", event: mod.MusicEvents.Radio_ClearQueue, key: "sxM55" },
            { name: "Radio_NextQueuedTrack", event: mod.MusicEvents.Radio_NextQueuedTrack, key: "sxM56" },
            { name: "Radio_Play", event: mod.MusicEvents.Radio_Play, key: "sxM57" },
        ],
        amp: { name: "Radio_Amplitude", param: mod.MusicParams.Radio_Amplitude, key: "sxM58", min: 0, max: 2, step: 0.1, def: 1 },
        params: [
            { name: "Radio_Biome", param: mod.MusicParams.Radio_Biome, key: "sxM59", min: 0, max: 10, step: 1, def: 0 },
            { name: "Radio_Channel", param: mod.MusicParams.Radio_Channel, key: "sxM60", min: 0, max: 10, step: 1, def: 0 },
            { name: "Radio_ContinueQueueOnTrackEnd", param: mod.MusicParams.Radio_ContinueQueueOnTrackEnd, key: "sxM61", min: 0, max: 1, step: 1, def: 1 },
            { name: "Radio_LoopQueuedTracks", param: mod.MusicParams.Radio_LoopQueuedTracks, key: "sxM62", min: 0, max: 1, step: 1, def: 0 },
            { name: "Radio_QueueTrackNumber", param: mod.MusicParams.Radio_QueueTrackNumber, key: "sxM63", min: 0, max: 20, step: 1, def: 0 },
        ],
    },
];
