// AUTO-GENERATED by tools/gen-scene.mjs - DO NOT EDIT BY HAND.
// Source: src/scene.json  (edit that file, then run: npm run gen)
//
// The Portal bundler cannot import .json (it inlines it as an invalid bare
// block), so the same data the browser preview renders is emitted here as a
// TypeScript module instead.

export interface SceneNode {
    k: "container" | "text" | "textbutton" | "button" | "repeat" | "group";
    id?: string;
    x: number;
    y: number;
    w?: number;
    h?: number;
    count?: number;
    gap?: number;
    gapX?: number;
    gapY?: number;
    cols?: number;
    template?: SceneNode | null;
    parent?: string;
    visible?: boolean;
    fill?: string;
    bg?: string;
    bgAlpha?: number;
    text?: string;
    textSize?: number;
    color?: string;
    textColor?: string;
    textAlpha?: number;
    align?: string;
    wrap?: boolean;
    enabled?: boolean;
    wScale?: string;
    bind?: Record<string, string>;
}

export const PALETTE: Readonly<Record<string, string>> = {
    "shell": "#0B0A10",
    "panel": "#161322",
    "row": "#241E36",
    "rowSel": "#4A2937",
    "line": "#2A2438",
    "hairline": "#4E4272",
    "ink": "#F7EBE2",
    "inkDim": "#CFC3CD",
    "muted": "#A8B4C4",
    "faint": "#8B96A4",
    "red": "#F04437",
    "redDim": "#8E241C",
    "blue": "#4A90F0",
    "green": "#3ED277",
    "amber": "#F5B443",
    "violet": "#A87BF0",
    "grey": "#7C838E",
    "headerBg": "#1E1A2E",
    "hot": "#FF7A1A",
    "redDeep": "#5C1A12",
    "orangeDim": "#A8480C"
};

export const GRID = {
    "cols": 1,
    "rows": 8,
    "rowW": 1316,
    "rowH": 58,
    "originX": 452,
    "originY": 304
} as const;

export const RAIL = {
    "x": 140,
    "y": 216,
    "w": 300,
    "h": 684,
    "rowsY": 262,
    "rowH": 32,
    "rowPadX": 6,
    "rowW": 288,
    "visibleRows": 18,
    "pagerY": 848,
    "pagerH": 28,
    "pagerW": 132
} as const;

export const RAIL_ROW: SceneNode = {
    "k": "textbutton",
    "x": 0,
    "y": 0,
    "w": 288,
    "h": 30,
    "text": "{{rail.label}}",
    "textSize": 13,
    "textColor": "{{rail.color}}",
    "bg": "{{rail.bg}}",
    "bgAlpha": 1,
    "align": "Left",
    "fill": "Solid"
};

export const RAIL_PAGER: readonly SceneNode[] = [
    {
        "k": "textbutton",
        "id": "btnRailPrev",
        "x": 146,
        "y": 848,
        "w": 132,
        "h": 28,
        "text": "< GROUPS",
        "textSize": 11,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "railPage",
        "x": 282,
        "y": 848,
        "w": 16,
        "h": 28,
        "text": "{{f.railPage}}",
        "textSize": 11,
        "textColor": "{{sh.muted}}",
        "align": "Center",
        "parent": "menu"
    },
    {
        "k": "textbutton",
        "id": "btnRailNext",
        "x": 302,
        "y": 848,
        "w": 132,
        "h": 28,
        "text": "GROUPS >",
        "textSize": 11,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    }
];

export const SCREEN: readonly SceneNode[] = [
    {
        "k": "group",
        "id": "menu",
        "x": 0,
        "y": 0,
        "visible": true,
        "bind": {
            "visible": "menuOpen"
        }
    },
    {
        "k": "group",
        "id": "browser",
        "x": 0,
        "y": 0,
        "visible": true,
        "bind": {
            "visible": "browserOn"
        },
        "parent": "menu"
    },
    {
        "k": "container",
        "x": 140,
        "y": 140,
        "w": 1640,
        "h": 800,
        "fill": "Solid",
        "bg": "{{sh.shell}}",
        "bgAlpha": 0.98,
        "parent": "menu"
    },
    {
        "k": "container",
        "x": 140,
        "y": 140,
        "w": 1640,
        "h": 76,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "menu"
    },
    {
        "k": "container",
        "x": 140,
        "y": 215,
        "w": 1640,
        "h": 1,
        "fill": "Solid",
        "bg": "{{sh.hairline}}",
        "bgAlpha": 1,
        "parent": "menu"
    },
    {
        "k": "container",
        "x": 140,
        "y": 215,
        "w": 300,
        "h": 684,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 439,
        "y": 215,
        "w": 1,
        "h": 684,
        "fill": "Solid",
        "bg": "{{sh.hairline}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 452,
        "y": 216,
        "w": 1316,
        "h": 46,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 452,
        "y": 261,
        "w": 1316,
        "h": 1,
        "fill": "Solid",
        "bg": "{{sh.hairline}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 452,
        "y": 262,
        "w": 1316,
        "h": 38,
        "fill": "Solid",
        "bg": "{{sh.shell}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 452,
        "y": 772,
        "w": 1316,
        "h": 48,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 452,
        "y": 824,
        "w": 1316,
        "h": 76,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "container",
        "x": 140,
        "y": 900,
        "w": 1640,
        "h": 40,
        "fill": "Solid",
        "bg": "{{sh.shell}}",
        "bgAlpha": 1,
        "parent": "menu"
    },
    {
        "k": "text",
        "x": 156,
        "y": 140,
        "w": 216,
        "h": 76,
        "text": "SFX / VFX SHOWCASE",
        "textSize": 20,
        "color": "{{sh.ink}}",
        "textAlpha": 1,
        "align": "Left",
        "parent": "menu"
    },
    {
        "k": "textbutton",
        "id": "tabSfx",
        "x": 512,
        "y": 152,
        "w": 124,
        "h": 56,
        "text": "SOUND",
        "textSize": 18,
        "textColor": "{{f.tabSfxColor}}",
        "bg": "{{f.tabSfxBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "tabVfx",
        "x": 644,
        "y": 152,
        "w": 124,
        "h": 56,
        "text": "VISUAL",
        "textSize": 18,
        "textColor": "{{f.tabVfxColor}}",
        "bg": "{{f.tabVfxBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "tabFav",
        "x": 776,
        "y": 152,
        "w": 140,
        "h": 56,
        "text": "FAVOURITES",
        "textSize": 14,
        "textColor": "{{f.tabFavColor}}",
        "bg": "{{f.tabFavBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "tabMusic",
        "x": 924,
        "y": 152,
        "w": 124,
        "h": 56,
        "text": "MUSIC",
        "textSize": 18,
        "textColor": "{{f.tabMusicColor}}",
        "bg": "{{f.tabMusicBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "tabRadio",
        "x": 1056,
        "y": 152,
        "w": 124,
        "h": 56,
        "text": "RADIO",
        "textSize": 18,
        "textColor": "{{f.tabRadioColor}}",
        "bg": "{{f.tabRadioBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "btnSelect",
        "x": 1188,
        "y": 152,
        "w": 164,
        "h": 56,
        "text": "{{f.selectLabel}}",
        "textSize": 15,
        "textColor": "{{sh.ink}}",
        "bg": "{{f.selectBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "browser",
        "bind": {
            "text": "selectLabel",
            "bg": "selectBg"
        },
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "armed",
        "x": 1360,
        "y": 142,
        "w": 192,
        "h": 52,
        "text": "{{f.armed}}",
        "textSize": 11,
        "color": "{{f.armedColor}}",
        "align": "Right",
        "wrap": true,
        "parent": "menu",
        "bind": {
            "text": "armed",
            "color": "armedColor"
        }
    },
    {
        "k": "textbutton",
        "id": "btnClose",
        "x": 1560,
        "y": 152,
        "w": 204,
        "h": 56,
        "text": "CLOSE X",
        "textSize": 18,
        "textColor": "{{sh.red}}",
        "bg": "{{sh.line}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "text",
        "x": 156,
        "y": 216,
        "w": 140,
        "h": 46,
        "text": "GROUP",
        "textSize": 13,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "browser"
    },
    {
        "k": "text",
        "id": "railCount",
        "x": 250,
        "y": 216,
        "w": 182,
        "h": 46,
        "text": "{{f.railSummary}}",
        "textSize": 11,
        "color": "{{sh.faint}}",
        "align": "Right",
        "parent": "browser",
        "bind": {
            "text": "railSummary"
        }
    },
    {
        "k": "container",
        "x": 156,
        "y": 260,
        "w": 268,
        "h": 1,
        "fill": "Solid",
        "bg": "{{sh.hairline}}",
        "bgAlpha": 1,
        "parent": "browser"
    },
    {
        "k": "text",
        "x": 694,
        "y": 262,
        "w": 560,
        "h": 38,
        "text": "NAME",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "browser"
    },
    {
        "k": "text",
        "x": 1108,
        "y": 262,
        "w": 230,
        "h": 38,
        "text": "GROUP",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "browser"
    },
    {
        "k": "text",
        "x": 1350,
        "y": 262,
        "w": 180,
        "h": 38,
        "text": "ACTION",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "browser"
    },
    {
        "k": "text",
        "x": 1542,
        "y": 262,
        "w": 226,
        "h": 38,
        "text": "{{f.headBadge}}",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Center",
        "parent": "browser",
        "bind": {
            "text": "headBadge"
        }
    },
    {
        "k": "textbutton",
        "id": "btnPrev",
        "x": 452,
        "y": 776,
        "w": 150,
        "h": 44,
        "text": "< PREV",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "browser",
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "pageLabel",
        "x": 640,
        "y": 776,
        "w": 940,
        "h": 44,
        "text": "{{f.page}}",
        "textSize": 15,
        "color": "{{sh.inkDim}}",
        "align": "Center",
        "parent": "browser",
        "bind": {
            "text": "page"
        }
    },
    {
        "k": "textbutton",
        "id": "btnNext",
        "x": 1618,
        "y": 776,
        "w": 150,
        "h": 44,
        "text": "NEXT >",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "browser",
        "fill": "Solid"
    },
    {
        "k": "group",
        "id": "sfxParams",
        "x": 462,
        "y": 828,
        "visible": true,
        "bind": {
            "visible": "sfxParams"
        },
        "parent": "browser"
    },
    {
        "k": "text",
        "x": 0,
        "y": 0,
        "w": 150,
        "h": 30,
        "text": "AMPLITUDE",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "sfxParams"
    },
    {
        "k": "textbutton",
        "id": "btnAmpDown",
        "x": 0,
        "y": 32,
        "w": 48,
        "h": 36,
        "text": "-",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "sfxParams",
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "txtAmp",
        "x": 54,
        "y": 32,
        "w": 90,
        "h": 36,
        "text": "{{f.amp}}",
        "textSize": 15,
        "color": "{{sh.amber}}",
        "align": "Center",
        "parent": "sfxParams",
        "bind": {
            "text": "amp"
        }
    },
    {
        "k": "textbutton",
        "id": "btnAmpUp",
        "x": 150,
        "y": 32,
        "w": 48,
        "h": 36,
        "text": "+",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "sfxParams",
        "fill": "Solid"
    },
    {
        "k": "text",
        "x": 216,
        "y": 0,
        "w": 110,
        "h": 30,
        "text": "RANGE m",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "sfxParams"
    },
    {
        "k": "textbutton",
        "id": "btnRngDown",
        "x": 216,
        "y": 32,
        "w": 48,
        "h": 36,
        "text": "-",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "sfxParams",
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "txtRng",
        "x": 270,
        "y": 32,
        "w": 90,
        "h": 36,
        "text": "{{f.rng}}",
        "textSize": 15,
        "color": "{{sh.amber}}",
        "align": "Center",
        "parent": "sfxParams",
        "bind": {
            "text": "rng"
        }
    },
    {
        "k": "textbutton",
        "id": "btnRngUp",
        "x": 366,
        "y": 32,
        "w": 48,
        "h": 36,
        "text": "+",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "sfxParams",
        "fill": "Solid"
    },
    {
        "k": "group",
        "id": "vfxParams",
        "x": 462,
        "y": 828,
        "visible": false,
        "bind": {
            "visible": "vfxParams"
        },
        "parent": "browser"
    },
    {
        "k": "text",
        "x": 0,
        "y": 0,
        "w": 90,
        "h": 30,
        "text": "SCALE",
        "textSize": 12,
        "color": "{{sh.muted}}",
        "align": "Left",
        "parent": "vfxParams"
    },
    {
        "k": "textbutton",
        "id": "btnScaleDown",
        "x": 0,
        "y": 32,
        "w": 48,
        "h": 36,
        "text": "-",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "vfxParams",
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "txtScale",
        "x": 54,
        "y": 32,
        "w": 110,
        "h": 36,
        "text": "{{f.scale}}",
        "textSize": 15,
        "color": "{{sh.amber}}",
        "align": "Center",
        "parent": "vfxParams",
        "bind": {
            "text": "scale"
        }
    },
    {
        "k": "textbutton",
        "id": "btnScaleUp",
        "x": 170,
        "y": 32,
        "w": 48,
        "h": 36,
        "text": "+",
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "vfxParams",
        "fill": "Solid"
    },
    {
        "k": "text",
        "x": 236,
        "y": 0,
        "w": 300,
        "h": 68,
        "text": "applies to the selected effect",
        "textSize": 11,
        "color": "{{sh.faint}}",
        "align": "Left",
        "wrap": true,
        "parent": "vfxParams"
    },
    {
        "k": "text",
        "id": "spawned",
        "x": 1020,
        "y": 828,
        "w": 240,
        "h": 68,
        "text": "{{f.spawned}}",
        "textSize": 12,
        "color": "{{sh.faint}}",
        "align": "Left",
        "wrap": true,
        "parent": "browser",
        "bind": {
            "text": "spawned"
        }
    },
    {
        "k": "textbutton",
        "id": "btnDebug",
        "x": 380,
        "y": 152,
        "w": 124,
        "h": 56,
        "text": "{{f.debugLabel}}",
        "textSize": 12,
        "textColor": "{{f.debugColor}}",
        "bg": "{{f.debugBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "menu",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "btnStopAll",
        "x": 1096,
        "y": 844,
        "w": 174,
        "h": 40,
        "text": "STOP ALL",
        "textSize": 14,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "browser",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "btnUndo",
        "x": 1280,
        "y": 844,
        "w": 180,
        "h": 40,
        "text": "UNDO",
        "textSize": 14,
        "textColor": "#FFFFFF",
        "bg": "{{sh.orangeDim}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "browser",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "btnDeleteAll",
        "x": 1470,
        "y": 844,
        "w": 260,
        "h": 40,
        "text": "DELETE ALL",
        "textSize": 14,
        "textColor": "#FFFFFF",
        "bg": "{{sh.redDeep}}",
        "bgAlpha": 1,
        "align": "Center",
        "parent": "browser",
        "fill": "Solid"
    },
    {
        "k": "text",
        "id": "hint",
        "x": 156,
        "y": 900,
        "w": 1608,
        "h": 40,
        "text": "{{f.hint}}",
        "textSize": 12,
        "color": "{{sh.faint}}",
        "align": "Left",
        "parent": "menu",
        "bind": {
            "text": "hint"
        }
    },
    {
        "k": "text",
        "x": 466,
        "y": 262,
        "w": 56,
        "h": 38,
        "text": "FAV",
        "textSize": 12,
        "textColor": "{{sh.muted}}",
        "align": "Center",
        "parent": "browser"
    },
    {
        "k": "group",
        "id": "tester",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "testerOn"
        },
        "parent": "menu"
    },
    {
        "k": "container",
        "x": 156,
        "y": 232,
        "w": 790,
        "h": 300,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "tester"
    },
    {
        "k": "container",
        "x": 962,
        "y": 232,
        "w": 802,
        "h": 460,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "tester"
    },
    {
        "k": "container",
        "x": 156,
        "y": 548,
        "w": 790,
        "h": 144,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "tester"
    },
    {
        "k": "container",
        "x": 156,
        "y": 708,
        "w": 1608,
        "h": 176,
        "fill": "Solid",
        "bg": "{{sh.panel}}",
        "bgAlpha": 1,
        "parent": "tester"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "id": "mtTitle",
        "x": 156,
        "y": 240,
        "w": 790,
        "h": 36,
        "text": "{{f.mtTitle}}",
        "textSize": 18,
        "bind": {
            "text": "mtTitle"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "x": 962,
        "y": 240,
        "w": 802,
        "h": 36,
        "text": "PARAMS",
        "textSize": 18
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "x": 156,
        "y": 554,
        "w": 790,
        "h": 30,
        "text": "VOLUME",
        "textSize": 18
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "x": 156,
        "y": 716,
        "w": 1608,
        "h": 32,
        "text": "LAST CALL",
        "textSize": 16
    },
    {
        "k": "group",
        "id": "mtPkgArrows",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtPkgArrows"
        },
        "parent": "tester"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtPkgArrows",
        "id": "mtPkgPrev",
        "x": 196,
        "y": 284,
        "w": 80,
        "h": 44,
        "text": "<",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtPkgArrows",
        "id": "mtPkgNext",
        "x": 866,
        "y": 284,
        "w": 80,
        "h": 44,
        "text": ">",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "id": "mtPkg",
        "x": 286,
        "y": 284,
        "w": 570,
        "h": 44,
        "text": "{{f.mtPkg}}",
        "textSize": 20,
        "bind": {
            "text": "mtPkg"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "id": "mtEvent",
        "x": 196,
        "y": 334,
        "w": 750,
        "h": 44,
        "text": "{{f.mtEvent}}",
        "textSize": 22,
        "bind": {
            "text": "mtEvent"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "id": "mtEventIdx",
        "x": 196,
        "y": 378,
        "w": 750,
        "h": 22,
        "text": "{{f.mtEventIdx}}",
        "textSize": 13,
        "bind": {
            "text": "mtEventIdx"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtPrev",
        "x": 196,
        "y": 406,
        "w": 180,
        "h": 60,
        "text": "{{f.mtPrevLabel}}",
        "textSize": 18,
        "bg": "{{sh.row}}",
        "bind": {
            "text": "mtPrevLabel"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtPlay",
        "x": 386,
        "y": 406,
        "w": 180,
        "h": 60,
        "text": "{{f.mtPlayLabel}}",
        "textSize": 18,
        "bg": "{{sh.green}}",
        "bind": {
            "text": "mtPlayLabel"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtStop",
        "x": 576,
        "y": 406,
        "w": 180,
        "h": 60,
        "text": "{{f.mtStopLabel}}",
        "textSize": 18,
        "bg": "{{sh.redDim}}",
        "bind": {
            "text": "mtStopLabel"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtNext",
        "x": 766,
        "y": 406,
        "w": 180,
        "h": 60,
        "text": "{{f.mtNextLabel}}",
        "textSize": 18,
        "bg": "{{sh.row}}",
        "bind": {
            "text": "mtNextLabel"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "id": "mtEventDesc",
        "x": 196,
        "y": 474,
        "w": 750,
        "h": 44,
        "text": "{{f.mtEventDesc}}",
        "textSize": 14,
        "bind": {
            "text": "mtEventDesc"
        }
    },
    {
        "k": "group",
        "id": "mtP0",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtP0On"
        },
        "parent": "tester"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Right",
        "color": "{{sh.ink}}",
        "parent": "mtP0",
        "id": "mtP0Label",
        "x": 978,
        "y": 282,
        "w": 330,
        "h": 44,
        "text": "{{f.mtP0Label}}",
        "textSize": 17,
        "bind": {
            "text": "mtP0Label"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "mtP0",
        "id": "mtP0Val",
        "x": 1318,
        "y": 282,
        "w": 130,
        "h": 44,
        "text": "{{f.mtP0Val}}",
        "textSize": 20,
        "bind": {
            "text": "mtP0Val"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP0",
        "id": "mtP0Down",
        "x": 1458,
        "y": 282,
        "w": 140,
        "h": 44,
        "text": "-",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP0",
        "id": "mtP0Up",
        "x": 1608,
        "y": 282,
        "w": 140,
        "h": 44,
        "text": "+",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Left",
        "color": "{{sh.muted}}",
        "parent": "mtP0",
        "id": "mtP0Desc",
        "x": 978,
        "y": 328,
        "w": 770,
        "h": 26,
        "text": "{{f.mtP0Desc}}",
        "textSize": 13,
        "bind": {
            "text": "mtP0Desc"
        }
    },
    {
        "k": "group",
        "id": "mtP1",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtP1On"
        },
        "parent": "tester"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Right",
        "color": "{{sh.ink}}",
        "parent": "mtP1",
        "id": "mtP1Label",
        "x": 978,
        "y": 360,
        "w": 330,
        "h": 44,
        "text": "{{f.mtP1Label}}",
        "textSize": 17,
        "bind": {
            "text": "mtP1Label"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "mtP1",
        "id": "mtP1Val",
        "x": 1318,
        "y": 360,
        "w": 130,
        "h": 44,
        "text": "{{f.mtP1Val}}",
        "textSize": 20,
        "bind": {
            "text": "mtP1Val"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP1",
        "id": "mtP1Down",
        "x": 1458,
        "y": 360,
        "w": 140,
        "h": 44,
        "text": "-",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP1",
        "id": "mtP1Up",
        "x": 1608,
        "y": 360,
        "w": 140,
        "h": 44,
        "text": "+",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Left",
        "color": "{{sh.muted}}",
        "parent": "mtP1",
        "id": "mtP1Desc",
        "x": 978,
        "y": 406,
        "w": 770,
        "h": 26,
        "text": "{{f.mtP1Desc}}",
        "textSize": 13,
        "bind": {
            "text": "mtP1Desc"
        }
    },
    {
        "k": "group",
        "id": "mtP2",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtP2On"
        },
        "parent": "tester"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Right",
        "color": "{{sh.ink}}",
        "parent": "mtP2",
        "id": "mtP2Label",
        "x": 978,
        "y": 438,
        "w": 330,
        "h": 44,
        "text": "{{f.mtP2Label}}",
        "textSize": 17,
        "bind": {
            "text": "mtP2Label"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "mtP2",
        "id": "mtP2Val",
        "x": 1318,
        "y": 438,
        "w": 130,
        "h": 44,
        "text": "{{f.mtP2Val}}",
        "textSize": 20,
        "bind": {
            "text": "mtP2Val"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP2",
        "id": "mtP2Down",
        "x": 1458,
        "y": 438,
        "w": 140,
        "h": 44,
        "text": "-",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP2",
        "id": "mtP2Up",
        "x": 1608,
        "y": 438,
        "w": 140,
        "h": 44,
        "text": "+",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Left",
        "color": "{{sh.muted}}",
        "parent": "mtP2",
        "id": "mtP2Desc",
        "x": 978,
        "y": 484,
        "w": 770,
        "h": 26,
        "text": "{{f.mtP2Desc}}",
        "textSize": 13,
        "bind": {
            "text": "mtP2Desc"
        }
    },
    {
        "k": "group",
        "id": "mtP3",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtP3On"
        },
        "parent": "tester"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Right",
        "color": "{{sh.ink}}",
        "parent": "mtP3",
        "id": "mtP3Label",
        "x": 978,
        "y": 516,
        "w": 330,
        "h": 44,
        "text": "{{f.mtP3Label}}",
        "textSize": 17,
        "bind": {
            "text": "mtP3Label"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "mtP3",
        "id": "mtP3Val",
        "x": 1318,
        "y": 516,
        "w": 130,
        "h": 44,
        "text": "{{f.mtP3Val}}",
        "textSize": 20,
        "bind": {
            "text": "mtP3Val"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP3",
        "id": "mtP3Down",
        "x": 1458,
        "y": 516,
        "w": 140,
        "h": 44,
        "text": "-",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP3",
        "id": "mtP3Up",
        "x": 1608,
        "y": 516,
        "w": 140,
        "h": 44,
        "text": "+",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Left",
        "color": "{{sh.muted}}",
        "parent": "mtP3",
        "id": "mtP3Desc",
        "x": 978,
        "y": 562,
        "w": 770,
        "h": 26,
        "text": "{{f.mtP3Desc}}",
        "textSize": 13,
        "bind": {
            "text": "mtP3Desc"
        }
    },
    {
        "k": "group",
        "id": "mtP4",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtP4On"
        },
        "parent": "tester"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Right",
        "color": "{{sh.ink}}",
        "parent": "mtP4",
        "id": "mtP4Label",
        "x": 978,
        "y": 594,
        "w": 330,
        "h": 44,
        "text": "{{f.mtP4Label}}",
        "textSize": 17,
        "bind": {
            "text": "mtP4Label"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "mtP4",
        "id": "mtP4Val",
        "x": 1318,
        "y": 594,
        "w": 130,
        "h": 44,
        "text": "{{f.mtP4Val}}",
        "textSize": 20,
        "bind": {
            "text": "mtP4Val"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP4",
        "id": "mtP4Down",
        "x": 1458,
        "y": 594,
        "w": 140,
        "h": 44,
        "text": "-",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "mtP4",
        "id": "mtP4Up",
        "x": 1608,
        "y": 594,
        "w": 140,
        "h": 44,
        "text": "+",
        "textSize": 20,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Left",
        "color": "{{sh.muted}}",
        "parent": "mtP4",
        "id": "mtP4Desc",
        "x": 978,
        "y": 640,
        "w": 770,
        "h": 26,
        "text": "{{f.mtP4Desc}}",
        "textSize": 13,
        "bind": {
            "text": "mtP4Desc"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "id": "mtParamNote",
        "x": 978,
        "y": 666,
        "w": 770,
        "h": 24,
        "text": "{{f.mtParamNote}}",
        "textSize": 12,
        "bind": {
            "text": "mtParamNote"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtVolDown",
        "x": 196,
        "y": 588,
        "w": 200,
        "h": 54,
        "text": "-",
        "textSize": 22,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.ink}}",
        "parent": "tester",
        "id": "mtVol",
        "x": 406,
        "y": 588,
        "w": 330,
        "h": 54,
        "text": "{{f.mtVol}}",
        "textSize": 26,
        "bind": {
            "text": "mtVol"
        }
    },
    {
        "k": "textbutton",
        "bgAlpha": 1,
        "align": "Center",
        "textColor": "#FFFFFF",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtVolUp",
        "x": 746,
        "y": 588,
        "w": 200,
        "h": 54,
        "text": "+",
        "textSize": 22,
        "bg": "{{sh.orangeDim}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "x": 156,
        "y": 648,
        "w": 790,
        "h": 30,
        "text": "Multiplier: 0 = silent, 1 = normal, 3 = triple volume.",
        "textSize": 13
    },
    {
        "k": "group",
        "id": "mtQueueGrp",
        "x": 0,
        "y": 0,
        "visible": false,
        "bind": {
            "visible": "mtQueueOn"
        },
        "parent": "tester"
    },
    {
        "k": "textbutton",
        "y": 756,
        "w": 260,
        "h": 48,
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bgAlpha": 1,
        "align": "Center",
        "fill": "Solid",
        "parent": "mtQueueGrp",
        "id": "mtQueue",
        "x": 466,
        "text": "{{f.mtQueueLabel}}",
        "bg": "{{sh.violet}}",
        "bind": {
            "text": "mtQueueLabel"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "mtQueueGrp",
        "x": 466,
        "y": 810,
        "w": 260,
        "h": 30,
        "text": "Adds the track number to the queue.",
        "textSize": 12
    },
    {
        "k": "textbutton",
        "y": 756,
        "w": 260,
        "h": 48,
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bgAlpha": 1,
        "align": "Center",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtTarget",
        "x": 1464,
        "text": "{{f.mtTargetLabel}}",
        "bg": "{{f.mtTargetBg}}",
        "bind": {
            "text": "mtTargetLabel",
            "bg": "mtTargetBg"
        }
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "x": 1464,
        "y": 810,
        "w": 260,
        "h": 30,
        "text": "ME: only you. EVERYONE: all players.",
        "textSize": 12
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.green}}",
        "parent": "tester",
        "id": "mtLast",
        "x": 736,
        "y": 756,
        "w": 718,
        "h": 48,
        "text": "{{f.mtLast}}",
        "textSize": 20,
        "bind": {
            "text": "mtLast"
        }
    },
    {
        "k": "textbutton",
        "y": 756,
        "w": 260,
        "h": 48,
        "textSize": 15,
        "textColor": "#FFFFFF",
        "bgAlpha": 1,
        "align": "Center",
        "fill": "Solid",
        "parent": "tester",
        "id": "mtSave",
        "x": 196,
        "text": "SAVE TEMPLATE",
        "bg": "{{sh.blue}}"
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "x": 196,
        "y": 810,
        "w": 260,
        "h": 30,
        "text": "Saves to FAVOURITES.",
        "textSize": 12
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "x": 736,
        "y": 810,
        "w": 718,
        "h": 30,
        "text": "The last call sent. The game cannot report what is playing.",
        "textSize": 12
    },
    {
        "k": "text",
        "textAlpha": 1,
        "align": "Center",
        "color": "{{sh.muted}}",
        "parent": "tester",
        "x": 196,
        "y": 846,
        "w": 1528,
        "h": 30,
        "text": "PLAY re-sends the package params and VOLUME before the event, so what you hear matches the numbers.",
        "textSize": 13
    }
];

export const ROW: readonly SceneNode[] = [
    {
        "k": "container",
        "id": "bg",
        "x": 0,
        "y": 0,
        "w": 1316,
        "h": 58,
        "fill": "Solid",
        "bg": "{{r.bg}}",
        "bgAlpha": 1,
        "bind": {
            "bg": "bg"
        }
    },
    {
        "k": "container",
        "x": 0,
        "y": 57,
        "w": 1316,
        "h": 1,
        "fill": "Solid",
        "bg": "{{sh.hairline}}",
        "bgAlpha": 1
    },
    {
        "k": "textbutton",
        "id": "fav",
        "x": 14,
        "y": 13,
        "w": 56,
        "h": 32,
        "text": "{{r.favLabel}}",
        "textSize": 15,
        "textColor": "{{r.favColor}}",
        "bg": "{{r.favBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "play",
        "x": 78,
        "y": 13,
        "w": 90,
        "h": 32,
        "text": "{{r.playLabel}}",
        "textSize": 14,
        "textColor": "{{r.playColor}}",
        "bg": "{{r.playBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "bind": {
            "text": "playLabel",
            "textColor": "playColor",
            "bg": "playBg"
        },
        "fill": "Solid"
    },
    {
        "k": "textbutton",
        "id": "stop",
        "x": 176,
        "y": 13,
        "w": 56,
        "h": 32,
        "text": "{{r.stopLabel}}",
        "textSize": 11,
        "textColor": "{{r.stopColor}}",
        "bg": "{{r.stopBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "fill": "Solid"
    },
    {
        "k": "text",
        "x": 242,
        "y": 0,
        "w": 402,
        "h": 58,
        "text": "{{r.name}}",
        "textSize": 18,
        "color": "{{r.nameColor}}",
        "align": "Left"
    },
    {
        "k": "text",
        "x": 656,
        "y": 0,
        "w": 230,
        "h": 58,
        "text": "{{r.category}}",
        "textSize": 12,
        "color": "{{sh.faint}}",
        "align": "Left"
    },
    {
        "k": "textbutton",
        "id": "sel",
        "x": 898,
        "y": 11,
        "w": 180,
        "h": 36,
        "text": "{{r.selLabel}}",
        "textSize": 15,
        "textColor": "{{r.selColor}}",
        "bg": "{{r.selBg}}",
        "bgAlpha": 1,
        "align": "Center",
        "bind": {
            "text": "selLabel",
            "textColor": "selColor",
            "bg": "selBg"
        },
        "fill": "Solid"
    },
    {
        "k": "container",
        "x": 1090,
        "y": 15,
        "w": 76,
        "h": 28,
        "fill": "Blur",
        "bg": "{{r.b1Bg}}",
        "bgAlpha": 0.34,
        "bind": {
            "bg": "b1Bg"
        }
    },
    {
        "k": "text",
        "x": 1090,
        "y": 15,
        "w": 76,
        "h": 28,
        "text": "{{r.b1}}",
        "textSize": 12,
        "color": "{{r.b1Color}}",
        "align": "Center"
    },
    {
        "k": "container",
        "x": 1174,
        "y": 15,
        "w": 128,
        "h": 28,
        "fill": "Blur",
        "bg": "{{r.b2Bg}}",
        "bgAlpha": 0.34,
        "bind": {
            "bg": "b2Bg"
        }
    },
    {
        "k": "text",
        "x": 1174,
        "y": 15,
        "w": 128,
        "h": 28,
        "text": "{{r.b2}}",
        "textSize": 12,
        "color": "{{r.b2Color}}",
        "align": "Center"
    }
];

export const KEYBOARD = {
    "x": 452,
    "y": 252,
    "w": 1316,
    "h": 500,
    "x0": 468,
    "keyW": 119,
    "keyH": 62,
    "gap": 10,
    "queryY": 272,
    "queryH": 56,
    "rowY": [
        360,
        430,
        500,
        570
    ],
    "rows": [
        "1234567890",
        "QWERTYUIOP",
        "ASDFGHJKL-",
        "ZXCVBNM.,_"
    ],
    "prefixGrid": {
        "x0": 468,
        "cols": 8,
        "rows": 7,
        "w": 153,
        "h": 36,
        "gap": 6,
        "rowY": [
            350,
            392,
            434,
            476,
            518,
            560,
            602
        ],
        "max": 56
    },
    "bottomY": 656,
    "bottomH": 62,
    "bottom": [
        {
            "action": "page",
            "label": "PREFIXES",
            "w": 280
        },
        {
            "action": "spc",
            "label": "SPACE",
            "w": 330
        },
        {
            "action": "bksp",
            "label": "BACK",
            "w": 170
        },
        {
            "action": "clr",
            "label": "CLEAR",
            "w": 170
        },
        {
            "action": "done",
            "label": "DONE",
            "w": 200
        }
    ]
} as const;

export const FILTERS = {
    "chipX": 460,
    "chipY": 222,
    "chipW": 124,
    "chipH": 38,
    "gap": 10,
    "searchX": 1486,
    "searchY": 222,
    "searchW": 254,
    "searchH": 38,
    "sfx": [
        {
            "label": "ALL",
            "key": "dim",
            "val": ""
        },
        {
            "label": "3D",
            "key": "dim",
            "val": "3d"
        },
        {
            "label": "2D",
            "key": "dim",
            "val": "2d"
        },
        {
            "label": "LOOP",
            "key": "kind",
            "val": "loop"
        },
        {
            "label": "ONE",
            "key": "kind",
            "val": "oneshot"
        }
    ],
    "vfx": [
        {
            "label": "ALL",
            "key": "vfx",
            "val": ""
        },
        {
            "label": "WORLD",
            "key": "vfx",
            "val": "world"
        },
        {
            "label": "PLAYER",
            "key": "vfx",
            "val": "screen"
        }
    ]
} as const;

export const CANVAS = {"w":1920,"h":1080} as const;

/**
 * Every action a click can produce, from the scene's own nodes.
 *
 * Emitted by the generator so check-actions.mjs can prove that handle() in
 * index.ts covers all of them. A clickable node's id IS its action: ui.ts passes
 * n.id straight through to ensureWidget(), which attaches it to the button.
 */
export const NODE_ACTIONS: readonly string[] = [
    "bksp",
    "btnAmpDown",
    "btnAmpUp",
    "btnClose",
    "btnDebug",
    "btnDeleteAll",
    "btnNext",
    "btnPrev",
    "btnRailNext",
    "btnRailPrev",
    "btnRngDown",
    "btnRngUp",
    "btnScaleDown",
    "btnScaleUp",
    "btnSelect",
    "btnStopAll",
    "btnUndo",
    "clr",
    "done",
    "mtNext",
    "mtP0Down",
    "mtP0Up",
    "mtP1Down",
    "mtP1Up",
    "mtP2Down",
    "mtP2Up",
    "mtP3Down",
    "mtP3Up",
    "mtP4Down",
    "mtP4Up",
    "mtPkgNext",
    "mtPkgPrev",
    "mtPlay",
    "mtPrev",
    "mtQueue",
    "mtSave",
    "mtStop",
    "mtTarget",
    "mtVolDown",
    "mtVolUp",
    "page",
    "spc",
    "tabFav",
    "tabMusic",
    "tabRadio",
    "tabSfx",
    "tabVfx"
];
